--------------------------------------------------------
--  DDL for Table CHARGER_STATIONS
--------------------------------------------------------
--DROP TABLE "CHARGER_STATIONS"
CREATE TABLE "CHARGER_STATIONS"
(
	"CHARGER_STATION_ID" NUMBER NOT NULL,
	"PETROL_STATION_ID" NUMBER NOT NULL,
    "CS_NUMBER" NUMBER(3),
    "CS_IS_USABLE" NUMBER(1,0) NOT NULL
);

--------------------------------------------------------
--  ADD CONSTRAINT TO CHARGER_STATIONS
--------------------------------------------------------
ALTER TABLE "CHARGER_STATIONS" ADD CONSTRAINT "CHARGER_STATION_ID_PK" PRIMARY KEY ("CHARGER_STATION_ID");

ALTER TABLE "CHARGER_STATIONS" ADD CONSTRAINT "CS_PET_FK" FOREIGN KEY ("PETROL_STATION_ID")
    REFERENCES "PETROL_STATIONS" ("PETROL_STATION_ID") ENABLE;
    
ALTER TABLE "CHARGER_STATIONS" ADD CONSTRAINT "CS_NUMBER_RANGE" CHECK (CS_NUMBER BETWEEN 0 AND 20) ENABLE;


--------------------------------------------------------
--  CREATE SEQUENCE FOR AUTO INCREMENT
--------------------------------------------------------

CREATE SEQUENCE SP_INSERT_CHARGER_STATION_SEQUENCE
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
--------------------------------------------------------
--  CREATE TRIGGER FOR CHARGER_STATION
--------------------------------------------------------
CREATE TRIGGER CHARGER_STATIONS_BI
BEFORE INSERT ON CHARGER_STATIONS
FOR EACH ROW
BEGIN
    SELECT SP_INSERT_CHARGER_STATION_SEQUENCE.nextval INTO :new.CHARGER_STATION_ID FROM dual;
END;
/

--------------------------------------------------------
--  POPULATE CHARGER_STATIONS
--------------------------------------------------------
INSERT INTO CHARGER_STATIONS (CHARGER_STATION_ID, PETROL_STATION_ID, CS_NUMBER, CS_IS_USABLE) VALUES ('1', '1', '1', '1');
INSERT INTO CHARGER_STATIONS (CHARGER_STATION_ID, PETROL_STATION_ID, CS_NUMBER, CS_IS_USABLE) VALUES ('2', '1', '2', '1');
INSERT INTO CHARGER_STATIONS (CHARGER_STATION_ID, PETROL_STATION_ID, CS_NUMBER, CS_IS_USABLE) VALUES ('3', '1', '3', '1');

INSERT INTO CHARGER_STATIONS (CHARGER_STATION_ID, PETROL_STATION_ID, CS_NUMBER, CS_IS_USABLE) VALUES ('4', '2', '1', '1');
INSERT INTO CHARGER_STATIONS (CHARGER_STATION_ID, PETROL_STATION_ID, CS_NUMBER, CS_IS_USABLE) VALUES ('5', '2', '2', '0');
INSERT INTO CHARGER_STATIONS (CHARGER_STATION_ID, PETROL_STATION_ID, CS_NUMBER, CS_IS_USABLE) VALUES ('6', '2', '3', '1');

INSERT INTO CHARGER_STATIONS (CHARGER_STATION_ID, PETROL_STATION_ID, CS_NUMBER, CS_IS_USABLE) VALUES ('7', '3', '1', '1');
INSERT INTO CHARGER_STATIONS (CHARGER_STATION_ID, PETROL_STATION_ID, CS_NUMBER, CS_IS_USABLE) VALUES ('8', '3', '2', '1');
INSERT INTO CHARGER_STATIONS (CHARGER_STATION_ID, PETROL_STATION_ID, CS_NUMBER, CS_IS_USABLE) VALUES ('9', '3', '3', '0');

INSERT INTO CHARGER_STATIONS (CHARGER_STATION_ID, PETROL_STATION_ID, CS_NUMBER, CS_IS_USABLE) VALUES ('10', '4', '1', '1');
INSERT INTO CHARGER_STATIONS (CHARGER_STATION_ID, PETROL_STATION_ID, CS_NUMBER, CS_IS_USABLE) VALUES ('11', '4', '2', '1');
INSERT INTO CHARGER_STATIONS (CHARGER_STATION_ID, PETROL_STATION_ID, CS_NUMBER, CS_IS_USABLE) VALUES ('12', '4', '3', '1');

INSERT INTO CHARGER_STATIONS (CHARGER_STATION_ID, PETROL_STATION_ID, CS_NUMBER, CS_IS_USABLE) VALUES ('13', '5', '1', '1');
INSERT INTO CHARGER_STATIONS (CHARGER_STATION_ID, PETROL_STATION_ID, CS_NUMBER, CS_IS_USABLE) VALUES ('14', '5', '2', '1');
INSERT INTO CHARGER_STATIONS (CHARGER_STATION_ID, PETROL_STATION_ID, CS_NUMBER, CS_IS_USABLE) VALUES ('15', '5', '3', '1');

INSERT INTO CHARGER_STATIONS (CHARGER_STATION_ID, PETROL_STATION_ID, CS_NUMBER, CS_IS_USABLE) VALUES ('16', '6', '1', '1');
INSERT INTO CHARGER_STATIONS (CHARGER_STATION_ID, PETROL_STATION_ID, CS_NUMBER, CS_IS_USABLE) VALUES ('17', '6', '2', '0');
INSERT INTO CHARGER_STATIONS (CHARGER_STATION_ID, PETROL_STATION_ID, CS_NUMBER, CS_IS_USABLE) VALUES ('18', '6', '3', '1');
