CREATE OR REPLACE VIEW VIEW_TEAMLEADERS
  AS 
        SELECT PS.PS_NAME, EMP.FULLNAME
        FROM PETROL_STATIONS PS
        INNER JOIN EMPLOYEES EMP ON PS.PETROL_STATION_ID = EMP.PETROL_STATION_ID
        WHERE IS_TEAMLEADER = 1;
   
   --SELECT PS.PETROL_STATION_ID, PS.PS_NAME, EMP.FULLNAME, (select count(CS.CHARGER_STATION_ID) FROM CHARGER_STATIONS CS WHERE CS.PETROL_STATION_ID = PS.PETROL_STATION_ID)
   --FROM PETROL_STATIONS PS
   --INNER JOIN EMPLOYEES EMP ON PS.PETROL_STATION_ID = EMP.PETROL_STATION_ID
   --WHERE IS_TEAMLEADER = 1