--------------------------------------------------------
--  File created - Monday-April-22-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "DEKANY"."EMPLOYEES" 
   (	"EMPLOYEE_ID" NUMBER, 
	"PETROL_STATION_ID" NUMBER, 
	"FULLNAME" VARCHAR2(100 BYTE), 
	"AGE" NUMBER DEFAULT NULL, 
	"JOB_TITLE" VARCHAR2(100 BYTE) DEFAULT NULL, 
	"IS_TEAMLEADER" NUMBER(1,0) DEFAULT 0
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into DEKANY.EMPLOYEES
SET DEFINE OFF;
Insert into DEKANY.EMPLOYEES (EMPLOYEE_ID,PETROL_STATION_ID,FULLNAME,AGE,JOB_TITLE,IS_TEAMLEADER) values (1,1,'Kiss Krisztián',30,'assistant',0);
Insert into DEKANY.EMPLOYEES (EMPLOYEE_ID,PETROL_STATION_ID,FULLNAME,AGE,JOB_TITLE,IS_TEAMLEADER) values (2,1,'Lukács István',25,'gas station attendant',0);
Insert into DEKANY.EMPLOYEES (EMPLOYEE_ID,PETROL_STATION_ID,FULLNAME,AGE,JOB_TITLE,IS_TEAMLEADER) values (3,1,'Gulyás János',27,'leader',1);
Insert into DEKANY.EMPLOYEES (EMPLOYEE_ID,PETROL_STATION_ID,FULLNAME,AGE,JOB_TITLE,IS_TEAMLEADER) values (4,2,'Király Zoltán',23,'assistant',0);
Insert into DEKANY.EMPLOYEES (EMPLOYEE_ID,PETROL_STATION_ID,FULLNAME,AGE,JOB_TITLE,IS_TEAMLEADER) values (5,2,'Katona Sándor',29,'gas station attendant',0);
Insert into DEKANY.EMPLOYEES (EMPLOYEE_ID,PETROL_STATION_ID,FULLNAME,AGE,JOB_TITLE,IS_TEAMLEADER) values (6,2,'Jakab Gábor',35,'leader',1);
Insert into DEKANY.EMPLOYEES (EMPLOYEE_ID,PETROL_STATION_ID,FULLNAME,AGE,JOB_TITLE,IS_TEAMLEADER) values (7,3,'Bogdán Ferenc',45,'assistant',0);
Insert into DEKANY.EMPLOYEES (EMPLOYEE_ID,PETROL_STATION_ID,FULLNAME,AGE,JOB_TITLE,IS_TEAMLEADER) values (8,3,'Balog Attila',26,'gas station attendant',0);
Insert into DEKANY.EMPLOYEES (EMPLOYEE_ID,PETROL_STATION_ID,FULLNAME,AGE,JOB_TITLE,IS_TEAMLEADER) values (9,3,'Boros Péter',29,'leader',1);
Insert into DEKANY.EMPLOYEES (EMPLOYEE_ID,PETROL_STATION_ID,FULLNAME,AGE,JOB_TITLE,IS_TEAMLEADER) values (10,4,'Fazekas Tamás',18,'assistant',0);
Insert into DEKANY.EMPLOYEES (EMPLOYEE_ID,PETROL_STATION_ID,FULLNAME,AGE,JOB_TITLE,IS_TEAMLEADER) values (11,4,'Kelemen Zsolt',27,'gas station attendant',0);
Insert into DEKANY.EMPLOYEES (EMPLOYEE_ID,PETROL_STATION_ID,FULLNAME,AGE,JOB_TITLE,IS_TEAMLEADER) values (12,4,'Váradi Tibor',29,'leader',1);
Insert into DEKANY.EMPLOYEES (EMPLOYEE_ID,PETROL_STATION_ID,FULLNAME,AGE,JOB_TITLE,IS_TEAMLEADER) values (13,5,'Antal András',25,'assistant',0);
Insert into DEKANY.EMPLOYEES (EMPLOYEE_ID,PETROL_STATION_ID,FULLNAME,AGE,JOB_TITLE,IS_TEAMLEADER) values (14,5,'Somogyi Csaba',21,'gas station attendant',0);
Insert into DEKANY.EMPLOYEES (EMPLOYEE_ID,PETROL_STATION_ID,FULLNAME,AGE,JOB_TITLE,IS_TEAMLEADER) values (15,5,'Orosz Imre',22,'leader',1);
Insert into DEKANY.EMPLOYEES (EMPLOYEE_ID,PETROL_STATION_ID,FULLNAME,AGE,JOB_TITLE,IS_TEAMLEADER) values (16,6,'Fülöp Lajos',20,'assistant',0);
Insert into DEKANY.EMPLOYEES (EMPLOYEE_ID,PETROL_STATION_ID,FULLNAME,AGE,JOB_TITLE,IS_TEAMLEADER) values (17,6,'Veres 	György',52,'gas station attendant',0);
Insert into DEKANY.EMPLOYEES (EMPLOYEE_ID,PETROL_STATION_ID,FULLNAME,AGE,JOB_TITLE,IS_TEAMLEADER) values (18,6,'Vincze Balázs',46,'leader',1);
--------------------------------------------------------
--  DDL for Index EMPLOYEE_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEKANY"."EMPLOYEE_ID_PK" ON "DEKANY"."EMPLOYEES" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger EMPLOYEES_AUTO_INCREMENT_BI
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "DEKANY"."EMPLOYEES_AUTO_INCREMENT_BI" 
BEFORE INSERT ON EMPLOYEES
FOR EACH ROW
BEGIN
    SELECT EMPLOYEES_SEQUENCE.nextval INTO :new.EMPLOYEE_ID FROM dual;
END;

/
ALTER TRIGGER "DEKANY"."EMPLOYEES_AUTO_INCREMENT_BI" ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "DEKANY"."EMPLOYEES" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "DEKANY"."EMPLOYEES" MODIFY ("PETROL_STATION_ID" NOT NULL ENABLE);
  ALTER TABLE "DEKANY"."EMPLOYEES" MODIFY ("FULLNAME" NOT NULL ENABLE);
  ALTER TABLE "DEKANY"."EMPLOYEES" ADD CONSTRAINT "EMPLOYEE_ID_PK" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "DEKANY"."EMPLOYEES" ADD CONSTRAINT "EMP_PET_FK" FOREIGN KEY ("PETROL_STATION_ID")
	  REFERENCES "DEKANY"."PETROL_STATIONS" ("PETROL_STATION_ID") ENABLE;
