--------------------------------------------------------
--  File created - Monday-April-22-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PETROL_STATION_HISTORIES
--------------------------------------------------------

  CREATE TABLE "DEKANY"."PETROL_STATION_HISTORIES" 
   (	"PETROL_STATION_HISTORY_ID" NUMBER, 
	"DML_TYPE" VARCHAR2(10 BYTE), 
	"ACTIVE_USER_ID" VARCHAR2(20 BYTE), 
	"PETROL_STATION_ID" NUMBER, 
	"SYSTEM_DATE" DATE, 
	"INFORMATION" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into DEKANY.PETROL_STATION_HISTORIES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index PETROL_STATION_HISTORY_ID_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "DEKANY"."PETROL_STATION_HISTORY_ID_PK" ON "DEKANY"."PETROL_STATION_HISTORIES" ("PETROL_STATION_HISTORY_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger PETROL_STATION_HISTORIES_BI
--------------------------------------------------------

  CREATE OR REPLACE NONEDITIONABLE TRIGGER "DEKANY"."PETROL_STATION_HISTORIES_BI" 
BEFORE INSERT ON PETROL_STATION_HISTORIES
FOR EACH ROW
BEGIN
    SELECT PETROL_STATION_HISTORIES_SEQUENCE.nextval INTO :new.PETROL_STATION_HISTORY_ID FROM dual;
END;

/
ALTER TRIGGER "DEKANY"."PETROL_STATION_HISTORIES_BI" ENABLE;
--------------------------------------------------------
--  Constraints for Table PETROL_STATION_HISTORIES
--------------------------------------------------------

  ALTER TABLE "DEKANY"."PETROL_STATION_HISTORIES" MODIFY ("PETROL_STATION_HISTORY_ID" NOT NULL ENABLE);
  ALTER TABLE "DEKANY"."PETROL_STATION_HISTORIES" MODIFY ("PETROL_STATION_ID" NOT NULL ENABLE);
  ALTER TABLE "DEKANY"."PETROL_STATION_HISTORIES" ADD CONSTRAINT "PETROL_STATION_HISTORY_ID_PK" PRIMARY KEY ("PETROL_STATION_HISTORY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PETROL_STATION_HISTORIES
--------------------------------------------------------

  ALTER TABLE "DEKANY"."PETROL_STATION_HISTORIES" ADD CONSTRAINT "PSHIST_PET_FK" FOREIGN KEY ("PETROL_STATION_ID")
	  REFERENCES "DEKANY"."PETROL_STATIONS" ("PETROL_STATION_ID") ENABLE;
